services:
  app:
    build:
      context: .
      target: production-main
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      target: production-websocket
    ports:
      - "8080:8080"
    env_file:
      - .env